import java.util.Random;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class DBubblesort extends javax.swing.JFrame 
{
    
    DefaultTableModel modelo1 =new DefaultTableModel();
    DefaultTableModel modelo2 =new DefaultTableModel();
    Metodos Met = new Metodos();
    int Num[]=new int[50];
    int i=0;
    boolean ordenado=false;
    boolean generado=false;
    public DBubblesort() {
        initComponents();
        modelo1.addColumn("Nro Fila");
        modelo1.addColumn("Ingresados");
        modelo2.addColumn("Nro Fila");
        modelo2.addColumn("Ordenados");
        tbIngr.setModel(modelo1);
        tbOrd.setModel(modelo2);
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngr = new javax.swing.JTable();
        txtNum = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnIngr = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbOrd = new javax.swing.JTable();
        btnGen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Método Bubblesort");

        tbIngr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbIngr);

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });
        txtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumKeyPressed(evt);
            }
        });

        btnOrdenar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Escriba solo números enteros y presione “Ingresar” para registrarlos  ");

        btnRestaurar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnIngr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIngr.setText("Ingresar ");
        btnIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngrActionPerformed(evt);
            }
        });

        tbOrd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbOrd);

        btnGen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGen.setText("Generar Números Aleatorios");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(btnIngr)
                                        .addGap(57, 57, 57)
                                        .addComponent(btnOrdenar)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnRestaurar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(btnAtras))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(btnGen)))
                                .addGap(51, 51, 51)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(56, 56, 56)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrdenar)
                            .addComponent(btnRestaurar)
                            .addComponent(btnIngr))
                        .addGap(60, 60, 60)
                        .addComponent(btnGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumKeyPressed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed
    private void btnIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngrActionPerformed
    if(txtNum.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No deje el campo de texto vacío");
        }
        else
        {
          int val=0;
          String cad[]= new String[2];
          cad[1]=txtNum.getText();
           try
           {
            val=Integer.parseInt(cad[1]);
            cad[0]=Integer.toString(i);;
            cad[1]=Integer.toString(val);
            modelo1.addRow(cad);
            Num[i]=val;
            
              if(ordenado==true)
               {
                for(int j=0;j<i;j++)
                {
                    modelo2.removeRow(0);
                }
                ordenado=false;
               }
            i++;         
           }
        catch(Exception e)
           {
            JOptionPane.showMessageDialog(null, "Ingrese solo Numeros Enteros o El numero en muy grande");
           }
        }
    }//GEN-LAST:event_btnIngrActionPerformed
    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

       if(i==0)
       {
          JOptionPane.showMessageDialog(null, "No hay números ingresados"); 
       }
       else
       {
           if(ordenado==true)
           {
            JOptionPane.showMessageDialog(null, "Los elementos ya fueron ordenados"); 
           }
           else
           {
           int arreglo[]=new int[i];
           String ord[]=new String[2];
           for(int j=0;j<i;j++)
           {
            arreglo[j]=Num[j];
           }
           arreglo=Met.Boubblesort(arreglo); //se llama al metodo de ordenamiento
            for(int k=0;k<i;k++)
            {
            ord[0]=Integer.toString(k);
            ord[1]=Integer.toString(arreglo[k]);
            modelo2.addRow(ord);
            }
            ordenado=true;
           }
       }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        txtNum.setText("");
        if(i!=0)
        {
         for(int j=0;j<i;j++)
        {
            modelo1.removeRow(0);
            if(ordenado==true)
            {
            modelo2.removeRow(0);
            }
            Num[j]=0;
        }
        i=0;
        ordenado=false;
        generado=false;
        }
 
    }//GEN-LAST:event_btnRestaurarActionPerformed
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        MenuPrincipal Mp=new MenuPrincipal();
        Mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        // TODO add your handling code here:
        
        if(generado==true)
        {
            JOptionPane.showMessageDialog(null, "Ya se han generado números aleatorios "); 
        }
        else
        {
          if(ordenado==true)
            {
                for(int j=0;j<i;j++)
                {
                    modelo2.removeRow(0);
                }
                ordenado=false;
            }  
        Random rd = new Random();
        int gen=0;
        String ale[]=new String[2];
        for(int j=i;j<i+500;j++)
        {
            gen=rd.nextInt(30);
            Num[j]=gen;
            ale[0]=Integer.toString(j);
            ale[1]=Integer.toString(gen);
            modelo1.addRow(ale);
        }
        i=i+15;
        generado=true;
        }
        
        
    }//GEN-LAST:event_btnGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMergesort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMergesort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMergesort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMergesort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBubblesort().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGen;
    private javax.swing.JButton btnIngr;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbIngr;
    private javax.swing.JTable tbOrd;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
